[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
test = "Ar6BaWBXb2PqXZZcaacSG6EFMfYAFU5pAX55gGunSPag"

[programs.localnet]
test = "Ar6BaWBXb2PqXZZcaacSG6EFMfYAFU5pAX55gGunSPag"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
